name: Firebase App Distribution
description: GitHub Action that uploads artifacts to Firebase App Distribution within seconds
author: Gowtham Raj
branding:
  icon: 'Purple'
  color: 'green'
inputs:
  file:
    description: The release binary file to upload.
    required: true
  appId:
    description: Your app's Firebase App ID. You can find the App ID in the Firebase console, on the General Settings page.
    required: true
  token:
    description: A refresh token that's printed when you authenticate your CI environment with the Firebase CLI (read Use the CLI with CI systems for more information).
    required: false
    deprecationMessage: Authenticating with `--token` is deprecated and will be removed in a future major version of `firebase-tools`. Instead, use a service account key with `GOOGLE_APPLICATION_CREDENTIALS` - https://cloud.google.com/docs/authentication/getting-started
  serviceCredentialsFileContent:
    description: Content of the service account credentials file
    required: false
  serviceCredentialsFile:
    description: Path to the Google service account credentials file
    required: false
  release-notes:
    description: Release notes for this build.
    required: false
  release-notes-file:
    description: Path to the file containing release notes for this build.
    required: false
  testers:
    description: The email addresses of the testers you want to invite.
    required: false
  testers-file:
    description: Path to the file containing the email addresses of the testers you want to invite.
    required: false
  groups:
    description: The tester groups you want to invite (refer to Manage testers). Groups are specified using group aliases, which you can look up in the Firebase console.
    required: false
  groups-file:
    description: Path to the file containing the tester groups you want to invite (refer to Manage testers). Groups are specified using group aliases, which you can look up in the Firebase console.
    required: false
  debug:
    description: A flag you can include to print verbose log output.
    required: false
    default: 'false'
  cache:
    description: Whether to cache the firebase tools for next job, keeping this on will speed up the build.
    required: false
    default: 'true'
  upgrade:
    description: Whether to attempt to upgrade firebase tools when cache is on, turning this off will speed up the build.
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Export content of credentials file as environment variable
      shell: bash
      if: ${{ inputs.serviceCredentialsFileContent == null && inputs.serviceCredentialsFile != null }}
      run: |
        echo "GOOGLE_APPLICATION_CREDENTIALS=${{ inputs.serviceCredentialsFile }}" >> $GITHUB_ENV
    
    - name: Export credentials as environment variable
      shell: bash
      if: ${{ inputs.serviceCredentialsFileContent != null }}
      run: |
        echo "GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/service-account.json" >> $GITHUB_ENV
    
    - name: Install Firebase CLI if not installed
      shell: bash
      run: |
            if ! command -v firebase &> /dev/null; then
              echo "Installing Firebase CLI with npm..."
              npm install -g firebase-tools --no-fund --no-audit --silent
            else
              echo "Firebase CLI already installed."
            fi
        
            if [[ "${{ inputs.upgrade }}" == "true" ]]; then
              echo "Upgrading Firebase CLI..."
              npm install -g firebase-tools@latest --no-fund --no-audit --silent
            fi
      
    - name: Firebase CLI version
      shell: bash 
      run: |        
            echo "Testing Firebase CLI..."
            firebase --version
    
    - name: Run firebase appdistribution:distribute 
      shell: bash
      run: |
        firebase appdistribution:distribute \
          --appId ${{ inputs.appId }} \
          --token "${{ inputs.token }}" \
          --release-notes "${{ inputs.release-notes }}" \
          --release-notes-file "${{ inputs.release-notes-file }}" \
          --testers "${{ inputs.testers }}" \
          --testers-file "${{ inputs.testers-file }}" \
          --groups "${{ inputs.groups }}" \
          --groups-file "${{ inputs.groups-file }}" \
          $(${{ inputs.debug }} && echo "--debug" || echo "") \
          ${{ inputs.file }}
